specVersion: 0.2.0
name: polkadot-extrinsics
version: 0.0.4
description: >-
  This projects collects all Polkadot extrinsics.
repository: https://github.com/lamafab/subql-dot-extrinsics
schema:
  file: ./schema.graphql
network:
  endpoint: wss://polkadot.api.onfinality.io/public-ws
  genesisHash: '0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3'
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleCall
          kind: substrate/CallHandler
