apiVersion: v1
kind: Service
metadata:
  name: {{ include "graphql.serviceName" . }}
  labels:
    app: {{ include "graphql.serviceName" . }}
spec:
  ports:
  - name: service
    port: {{ .Values.graphql.config.port }}
  selector:
    app: {{ include "graphql.deploymentName" . }}
