apiVersion: v1
kind: Service
metadata:
  name: {{ include "indexer.serviceName" . }}
  labels:
    app: {{ include "indexer.serviceName" . }}
spec:
  ports:
  - name: service
    port: {{ .Values.indexer.config.port }}
  selector:
    app: {{ include "indexer.deploymentName" . }}
