
environments:
  production:
  ci:
  local:
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
releases:
  - name: postgres
    chart: bitnami/postgresql
    version: 11.1.3
    namespace: alessio-test-subql
    values:
      - ./config/postgresql-14-values.yaml.gotmpl